spring.application.name=auth-service
server.port=8081

spring.main.allow-bean-definition-overriding=true

twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.path-service-id=${TWILIO_PATH_SERVICE_ID}

totp.issuer=Lynk
totp.period=30

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/authentication
spring.r2dbc.pool.enabled=true
spring.r2dbc.username=postgres
spring.r2dbc.pool.max-size=10
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.schema-locations=classpath:schema.sql

keystore.type=PKCS12
keystore.path=classpath:jwt_key.pkcs12
keystore.password=${KEYSTORE_PASSWORD}
keystore.alias=JWT_KEY_ALIAS

token.access.expiration=300000
token.refresh.expiration=604800000

google.oauth.client.id=${CLIENT_ID}
google.oauth.client.secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

logging.level.org.springframework.cloud.stream=DEBUG
spring.cloud.stream.bindings.userCreated-out-0.destination=user-created
spring.cloud.stream.bindings.userCreated-out-0.content-type=application/json