spring.application.name=notification-service
server.port=8083

app.firebase-configuration-file=lynk-fcm.json

spring.r2dbc.url=r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

spring.kafka.consumer.bootstrap-servers=${spring.kafka.host}:9094
spring.kafka.host=${KAFKA_HOST:localhost}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.ack-mode=manual_immediate
spring.kafka.properties.security.protocol=SSL

# Truststore
spring.kafka.properties.ssl.truststore.location=kafka.truststore.jks
spring.kafka.properties.ssl.truststore.password=${KAFKA_SSL_TRUSTSTORE_PASSWORD}
spring.kafka.properties.ssl.truststore.type=JKS

# Keystore (client authentication)
spring.kafka.properties.ssl.keystore.location=kafka.keystore.pkcs12
spring.kafka.properties.ssl.keystore.password=${KAFKA_SSL_KEYSTORE_PASSWORD}
spring.kafka.properties.ssl.key.password=${KAFKA_SSL_KEY_PASSWORD}
spring.kafka.properties.ssl.keystore.type=PKCS12 # Explicitly specify type

spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}
spring.r2dbc.name=${DB_NAME}