services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  cassandra:
    image: scylladb/scylla
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "message"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_START_RPC: "true"
    ports:
      - "9042:9042"
      - "9160:9160"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - cassandra_data:/var/lib/cassandra

  redis:
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: redis:latest
    container_name: redis
    ports:
        - "6379:6379"
    volumes:
      - redis_data:/data

  auth-service:
    build:
      context: ./auth-service
      args:
        GRADLE_USER_HOME: /root/.gradle-auth
    container_name: auth-service
    image: auth-service
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: auth_db
      DB_PORT: 5432
      DB_HOST: postgres
      MAIL_HOST: mailhog
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_KEYSTORE_LOCATION: keystore.jks
      JWT_KEYSTORE_PASSWORD: ${JWT_KEYSTORE_PASSWORD}
      JWT_KEY_PASSWORD: ${JWT_KEY_PASSWORD}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    ports:
      - "8081:8081"

  message-service:
    build:
      context: ./message-service
      args:
        GRADLE_USER_HOME: /root/.gradle-message
    container_name: message-service
    image: message-service
    depends_on:
      cassandra: { condition: service_healthy }
      redis: { condition: service_healthy }
    environment:
        CASSANDRA_HOST: cassandra
        CASSANDRA_PORT: 9042
        REDIS_HOST: redis
        JWT_KEYSTORE_LOCATION: keystore.jks
        JWT_KEYSTORE_PASSWORD: ${JWT_KEYSTORE_PASSWORD}
        JWT_KEY_PASSWORD: ${JWT_KEY_PASSWORD}
        REDIS_PORT: 6379
    ports:
      - "8082:8082"

volumes:
  postgres_data:
  redis_data:
  cassandra_data: