spring.application.name=message-service
server.port=8082

#ElasticSearch
spring.elasticsearch.username=${ELASTICSEARCH_USERNAME}
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD}

#ScyllaDB
#spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
#spring.cassandra.request.timeout=10s
#spring.cassandra.connection.connect-timeout=10s
#spring.cassandra.connection.init-query-timeout=10s
#spring.cassandra.local-datacenter=datacenter1
#spring.cassandra.keyspace-name=message

spring.cassandra.username=token
spring.cassandra.keyspace-name=default_keyspace
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s

spring.cassandra.password=AstraCS:JDbNnSjAumnsMgxAtZZcYqPM:b4a0afa095bf23732d65c58974d3eb16ac2ee0a4ae2ea3739c8bb1f1102b55c6
datastax.astra.secure-connect-bundle=/home/rishabh/Backend/Lynk/message-service/src/main/resources/secure-connect-message.zip

file.upload-dir=/home/rishabh/Backend/Lynk/message-service/src/main/resources/uploads