spring.application.name=message-service

#ElasticSearch
spring.elasticsearch.username=${ELASTICSEARCH_USERNAME}
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD}

# RSocket
spring.rsocket.server.port=7000
spring.rsocket.server.transport=websocket

#ScyllaDB
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=message