spring.application.name=gateway-service

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes=[object Object], [object Object]
spring.cloud.loadbalancer.configurations=zone-preference
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true

user-bloom-filter.capacity=100000
user-bloom-filter.key=user:status

jedis.url=redis://localhost:6379

server.port=8080
grpc.client.local-grpc-server.address=static://127.0.0.1:9898
grpc.client.local-grpc-server.enableKeepAlive=true
grpc.client.local-grpc-server.keepAliveWithoutCalls=true
grpc.client.local-grpc-server.negotiationType=plaintext
